### ISSUE TITLE
Untrustworthy Dependency

### ISSUE THREAD

**Issue by thisisntsafe** [brave/store-brave-com#290]
### Describe the bug

https://github.com/brave/store-brave-com/blob/staging/package.json#L40 libphonenumber-js

This repo is 550kb, compressed. The author is based in Moscow, Russia and has had his account banned from Github. His CV includes working for "Russian NSA-like system for intercepting communication on the internet with the purpose of preventing governmental threats".
https://docs.google.com/document/d/1B2C1IGwZjXTxdogOvE5vejcBx0kKe1ynHXzPxQcv6x4/edit

This author posts Z-propaganda on his VK page. https://vk.com/catamphetamine

I would recommend finding a more trustworthy dependency for this.

### Reproduction

https://github.com/brave/store-brave-com/blob/staging/package.json#L40 libphonenumber-js

Package home is https://www.npmjs.com/package/libphonenumber-js
Code repo linked is https://gitlab.com/catamphetamine/libphonenumber-js
Author page is https://gitlab.com/catamphetamine
CV linked in bottom right under "Contact": https://goo.gl/0InMpC

### System Info

- OS: all
- Browser: all

### Severity

serious, but I can still use the site

**Comment by AlanBreck** [comment]
Thank you for your report. We’ve looked into the code and determined that we’re not at risk by using this library.
